import express from 'express';
import usersRoutes from './usersRoutes.js';
import orderRoutes from './orderRoutes.js';
import likeRoutes from './likeRoutes.js';
import rateRoutes from './rateRoutes.js';
const rootRoutes = express.Router();
rootRoutes.use('/users',usersRoutes);
rootRoutes.use('/orders',orderRoutes);
rootRoutes.use('/like',likeRoutes);
rootRoutes.use('rate', rateRoutes);
export default rootRoutes;